// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// not_able_knots
Rcpp::NumericVector not_able_knots(Rcpp::NumericMatrix all, int delta);
RcppExport SEXP _splineSelection_not_able_knots(SEXP allSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type all(allSEXP);
    Rcpp::traits::input_parameter< int >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(not_able_knots(all, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_splineSelection_not_able_knots", (DL_FUNC) &_splineSelection_not_able_knots, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_splineSelection(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
